// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkgjchxlysgjmgswgxnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZ2pjaHhseXNnam1nc3dneG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTA0NDgsImV4cCI6MjA2NTU2NjQ0OH0.2T5_0lwjXsav-POp5qZoc2p4C72JsYCHynjEnTrqDcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);